In [1]:
import IOHMM
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
n_components = 2
startprob = np.array([0.2, 0.8])

sd_noise = 0.25
poisson_mean = 2.0
sample_size = 5
Y = np.random.poisson(poisson_mean, sample_size)
X1 = np.floor(3 * Y + 2 + np.random.normal(0, sd_noise, sample_size))
X2 = np.floor(7 * Y + 5 + np.random.normal(0, sd_noise, sample_size))
X = np.matrix(np.vstack((X1, X2)))
X = X.transpose()

print(X.shape)
print(Y.shape)

hmm = IOHMM._BaseIOHMM(n_components, [X], [Y], start_prob=startprob)

hmm.fit()

(5, 2)
(5,)
-----log_trans_mat--- 
 [[[0.39245375 0.60754625]
  [0.65161621 0.34838379]]

 [[0.48245236 0.51754764]
  [0.61393555 0.38606445]]

 [[0.2280302  0.7719698 ]
  [0.72614237 0.27385763]]

 [[0.56363051 0.43636949]
  [0.58152854 0.41847146]]

 [[0.66001498 0.33998502]
  [0.53478244 0.46521756]]]
--------trans_posts-------- 
 [[[0.0922315  0.0896305 ]
  [0.6125516  0.2055864 ]]

 [[0.43106614 0.27371696]
  [0.21513827 0.08007862]]

 [[0.10602632 0.5401781 ]
  [0.22569703 0.12809856]]

 [[0.18992842 0.14179493]
  [0.39451628 0.27376037]]

 [[0.36212555 0.22231915]
  [0.20402465 0.21153065]]]
0 --------------log_prob--------- 
 -6.950049209991448
-----log_trans_mat--- 
 [[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]]
--------trans_posts-------- 
 [[[0.20072794 0.        ]
  [0.         0.79927206]]

 [[0.20072794 0.        ]
  [0.79927206 0.        ]]

 [[0.         1.        ]
  [0.         0.        ]]

 [[0.        

In [5]:
print(Y)
hmm._test_predictions()

[3 2 5 1 0]


[matrix([[1.55012405]]),
 matrix([[0.]]),
 matrix([[4.28765491]]),
 matrix([[0.]]),
 matrix([[0.48500646]])]

In [6]:
hmm.viterbi()

4
3
2
1
0


[1, 0, 1, 0, 1, 1]