In [1]:
import IOHMM
import numpy as np
import pandas as pd

In [3]:
np.random.seed(0)
n_components = 2
startprob = np.array([0.2, 0.8])

sd_noise = 0.25
poisson_mean = 2.0
sample_size = 200
Y = np.random.poisson(poisson_mean, sample_size)
X1 = np.floor(3 * Y + 2 + np.random.normal(0, sd_noise, sample_size))
X2 = np.floor(7 * Y + 5 + np.random.normal(0, sd_noise, sample_size))
X = np.matrix(np.vstack((X1, X2)))
X = X.transpose()

print(X.shape)
print(Y.shape)

hmm = IOHMM._BaseIOHMM(n_components, [X], [Y], start_prob=startprob)

hmm.fit()

(200, 2)
(200,)
-----log_trans_mat--- 
 [[[0.36241724 0.63758276]
  [0.41834222 0.58165778]]

 [[0.37049284 0.62950716]
  [0.30267994 0.69732006]]

 [[0.3322732  0.6677268 ]
  [0.71291732 0.28708268]]

 [[0.38773377 0.61226623]
  [0.18327736 0.81672264]]

 [[0.39878132 0.60121868]
  [0.11989096 0.88010904]]

 [[0.40201663 0.59798337]
  [0.11167486 0.88832514]]

 [[0.30629903 0.69370097]
  [0.88780262 0.11219738]]

 [[0.38773377 0.61226623]
  [0.18327736 0.81672264]]

 [[0.35666196 0.64333804]
  [0.43656339 0.56343661]]

 [[0.35976003 0.64023997]
  [0.41692625 0.58307375]]

 [[0.33526983 0.66473017]
  [0.69620946 0.30379054]]

 [[0.37364128 0.62635872]
  [0.28600807 0.71399193]]

 [[0.37634074 0.62365926]
  [0.28719842 0.71280158]]

 [[0.40201663 0.59798337]
  [0.11167486 0.88832514]]

 [[0.38453948 0.61546052]
  [0.19560142 0.80439858]]

 [[0.36241724 0.63758276]
  [0.41834222 0.58165778]]

 [[0.387269   0.612731  ]
  [0.19651907 0.80348093]]

 [[0.37318311 0.62681689]
  [0.30391014 0.