In [1]:
# Usefull imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
from hmmlearn import hmm
from IOHMM import IOHMM_model

In [2]:
hmm_model = hmm.GaussianHMM(n_components=2, covariance_type="diag", n_iter=100)

hmm_model.startprob_ = np.array([0.2, 0.8])

hmm_model.transmat_ = np.array([[0.4, 0.6],
                                [0.2, 0.8]])

hmm_model.means_ = np.array([[-10.0], [10.0]])

hmm_model.covars_ = np.array([[.1], [.1]])


In [3]:
#sample data
X, Z = hmm_model.sample(5)

#dataframe
data = pd.DataFrame(X, columns=['X'])
data['Z'] = Z

data[:]

X  Z
0   9.817732  1
1  10.000002  1
2  -9.556336  0
3   9.936877  1
4 -10.195306  0

In [4]:
# Torch  data
output = torch.tensor(data['X'].values, dtype=torch.float32)
# Input data ones
input = torch.ones(output.size(), dtype=torch.float32).unsqueeze(1)

In [5]:
# Transition matrix
TM = torch.tensor([[[1., 2.2],
                    [-1., 3.1]],
                    
                    [[1., 2.],
                    [-1.3, 3.]]], dtype=torch.float32)


IOHMM = IOHMM_model(num_states=2, inputs=input, outputs=output, max_iter=10, tol=1e-40)

In [6]:
IOHMM._baum_welch()

zeta[0]: tensor([0.5000, 0.5000])
iter: 0, likelihood: -30.01453971862793, likelihood marco: -108.60868835449219
zeta[0]: tensor([0.5000, 0.5000])
iter: 1, likelihood: -30.01453971862793, likelihood marco: -108.60868835449219
convergence reached :)
final likelihood: -30.01453971862793


In [7]:
matrix=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
vector=torch.tensor([1,2,3])
print(vector.shape)
print(matrix.shape)
sum_vector=vector+matrix
print(sum_vector)
torch.sum(sum_vector, dim=0)

torch.Size([3])
torch.Size([3, 3])
tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])


tensor([15, 21, 27])

In [8]:
IOHMM.viterbi()

tensor([0, 0, 1, 0, 1])