## Implementation

In [1]:
from IOHMM import IOHMM_model
import numpy as np, pandas as pd
import torch

In [2]:
data = pd.read_csv("data/Financial-Data/stocks/TSLA.csv")
data.head()
data = data.dropna()

input = torch.tensor(np.array(data[['Open']]), dtype=torch.float32)
output = torch.tensor(np.array(data['Close']), dtype=torch.float32)

# Example 1

## Set up a simple model manully

In [3]:
IOHMM = IOHMM_model(num_states=2, inputs=input[:10], outputs=output[:10], max_iter=100, tol=1e-3)
print(IOHMM.initial_pi)
print(IOHMM.transition_matrix)
print(IOHMM.emission_matrix)
print(IOHMM.sd)

Parameter containing:
tensor([0.5000, 0.5000], requires_grad=True)
Parameter containing:
tensor([[[ 0.5382,  0.2197],
         [ 0.3415, -0.5765]],

        [[-1.3019,  1.5715],
         [ 0.8606, -0.7692]]], requires_grad=True)
Parameter containing:
tensor([[ 0.7458,  0.5826],
        [-0.9079,  0.4964]], requires_grad=True)
Parameter containing:
tensor([1., 1.], requires_grad=True)


In [4]:
print(IOHMM._forward())
torch.sum(IOHMM._forward(), dim=1)

tensor([[0.8515, 0.1485],
        [0.9500, 0.0500],
        [0.9367, 0.0633],
        [0.9146, 0.0854],
        [0.8810, 0.1190],
        [0.8732, 0.1268],
        [0.8924, 0.1076],
        [0.8940, 0.1060],
        [0.8904, 0.1096],
        [0.9017, 0.0983]])


tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000])

In [5]:
print(IOHMM._backward())
torch.sum(IOHMM._backward(), dim=1)

tensor([[0.9492, 0.0508],
        [0.9488, 0.0512],
        [0.9371, 0.0629],
        [0.9147, 0.0853],
        [0.8796, 0.1204],
        [0.8743, 0.1257],
        [0.8938, 0.1062],
        [0.8935, 0.1065],
        [0.8832, 0.1168],
        [0.7625, 0.2375]])


tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000])

In [6]:
print(IOHMM._compute_gamma(IOHMM._forward(), IOHMM._backward()))
torch.sum(IOHMM._compute_gamma(IOHMM._forward(), IOHMM._backward()), dim=1)

tensor([[0.9908, 0.0092],
        [0.9972, 0.0028],
        [0.9955, 0.0045],
        [0.9914, 0.0086],
        [0.9818, 0.0182],
        [0.9795, 0.0205],
        [0.9859, 0.0141],
        [0.9861, 0.0139],
        [0.9840, 0.0160],
        [0.9672, 0.0328]])


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
print(IOHMM._compute_xi(IOHMM._forward(), IOHMM._backward()))
a = torch.sum(IOHMM._compute_xi(IOHMM._forward(), IOHMM._backward()), axis=1)
torch.sum(a, axis=1)

tensor([[[8.9592e-01, 8.7623e-02],
         [1.4354e-02, 2.1003e-03]],

        [[8.3657e-01, 1.5272e-01],
         [9.4276e-03, 1.2798e-03]],

        [[9.3473e-01, 5.1009e-02],
         [1.3662e-02, 6.0136e-04]],

        [[9.1593e-01, 6.1982e-02],
         [2.0703e-02, 1.3885e-03]],

        [[8.8490e-01, 7.6657e-02],
         [3.4415e-02, 4.0239e-03]],

        [[8.5576e-01, 9.2915e-02],
         [4.2334e-02, 8.9877e-03]],

        [[8.5751e-01, 9.8754e-02],
         [3.5517e-02, 8.2149e-03]],

        [[8.7133e-01, 8.9171e-02],
         [3.3557e-02, 5.9468e-03]],

        [[8.6866e-01, 8.8737e-02],
         [3.6407e-02, 6.1995e-03]],

        [[8.1709e-01, 8.4634e-02],
         [8.3081e-02, 1.5196e-02]]])


tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000])

In [8]:
IOHMM._baum_welch()

Iteration:  0 
Initial pi:
 Parameter containing:
tensor([0.6149, 0.5111], requires_grad=True) 
Transition matrix:
 Parameter containing:
tensor([[[ 0.5382,  0.2197],
         [ 0.3415, -0.5765]],

        [[-1.3019,  1.5715],
         [ 0.8606, -0.7692]]], requires_grad=True) 
Emission matrix:
 Parameter containing:
tensor([[ 0.7458,  0.5826],
        [-0.9079,  0.4964]], requires_grad=True) 
Standard deviation:
 Parameter containing:
tensor([1., 1.], requires_grad=True)
Iteration:  1 
Initial pi:
 Parameter containing:
tensor([0.7504, 0.5202], requires_grad=True) 
Transition matrix:
 Parameter containing:
tensor([[[ 0.5382,  0.2197],
         [ 0.3415, -0.5765]],

        [[-1.3019,  1.5715],
         [ 0.8606, -0.7692]]], requires_grad=True) 
Emission matrix:
 Parameter containing:
tensor([[ 0.7458,  0.5826],
        [-0.9079,  0.4964]], requires_grad=True) 
Standard deviation:
 Parameter containing:
tensor([1., 1.], requires_grad=True)
Iteration:  2 
Initial pi:
 Parameter containi

## See the training results

In [9]:
print("Initial pi")
print(IOHMM.initial_pi) # to normalize
print("Transition matrix")
print(IOHMM.transition_matrix)
print("Emission matrix")
print(IOHMM.emission_matrix)
print("Sd")
print(IOHMM.sd)

Initial pi
Parameter containing:
tensor([10027872.0000,    39974.0742], requires_grad=True)
Transition matrix
Parameter containing:
tensor([[[ 0.5382,  0.2197],
         [ 0.3415, -0.5765]],

        [[-1.3019,  1.5715],
         [ 0.8606, -0.7692]]], requires_grad=True)
Emission matrix
Parameter containing:
tensor([[ 0.7458,  0.5826],
        [-0.9079,  0.4964]], requires_grad=True)
Sd
Parameter containing:
tensor([1., 1.], requires_grad=True)


## Viterbi

In [10]:
#call the viterbi algorithm
IOHMM.viterbi()

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Predict

In [11]:
# predict the next output given the next input
IOHMM.predict(input[11])


tensor(0.9799, grad_fn=<SumBackward0>)

In [12]:
output[11]

tensor(1.3260)